kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: Build
    image: openjdk:22-oracle
    commands:
      - |
        if command -v apt-get &> /dev/null; then
          echo "This system uses APT package manager"
          apt-get update && apt-get install -y findutils
        elif command -v yum &> /dev/null; then
          echo "This system uses YUM package manager"
          yum install -y findutils
        elif command -v dnf &> /dev/null; then
          echo "This system uses DNF package manager"
          dnf install -y findutils
        elif command -v apk &> /dev/null; then
          echo "This system uses APK package manager"
          apk add --no-cache findutils
        else
          echo "Could not determine package manager"
        fi
      - chmod +x gradlew
      - ./gradlew build